version: '3'
services:
  tensorflow-serving:
    build:
      context: .
      dockerfile: Dockerfile.2
    container_name: TF_serving_container
    ports:
      - "8601:8501"
    command: tensorflow_model_server --rest_api_port=8501 --model_config_file="/models/model/models.config.b"
    networks:
      - ml_network
          
  flask-app:
    build: .
    ports:
      - "9090:8080"
    container_name: app_container
    depends_on:
      - tensorflow-serving
    networks:
      - ml_network
    #volumes:
    #  - C:\\Users\Eye patch\Desktop\project DL deployement\APP\static:/DL_project/APP/static
    #  - C:\\Users\Eye patch\Desktop\project DL deployement\database\:/DL_project/database

networks:
  ml_network:
    driver: bridge
